bind-interfaces
interface=brvlan10
interface=brvlan20
except-interface=lo
domain=campus.lab
dhcp-range=set:alumnos,192.168.10.100,192.168.10.199,255.255.255.0,1h
dhcp-range=set:docentes,192.168.20.100,192.168.20.199,255.255.255.0,1h
dhcp-option=tag:alumnos,option:router,192.168.10.1
dhcp-option=tag:docentes,option:router,192.168.20.1
dhcp-option=tag:alumnos,option:dns-server,192.168.10.1
dhcp-option=tag:docentes,option:dns-server,192.168.20.1
address=/portal.campus.lab/192.168.10.1
server=1.1.1.1
interface=brvlan30
dhcp-range=set:invitados,192.168.30.100,192.168.30.199,255.255.255.0,30m
dhcp-option=tag:invitados,option:router,192.168.30.1
dhcp-option=tag:invitados,option:dns-server,192.168.30.1
