interface=wlan0
driver=nl80211
ssid=UNCUYO-EDU
hw_mode=g
channel=1
ieee8021x=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
own_ip_addr=127.0.0.1
nas_identifier=ap-lab
auth_server_addr=127.0.0.1
auth_server_port=1812
auth_server_shared_secret=testing123
ctrl_interface=/run/hostapd
dynamic_vlan=2
vlan_file=/etc/hostapd/tp7.vlan

bss=wlan0_1
ssid=UNCUYO-INVITADOS
bridge=brvlan30
ctrl_interface=/run/hostapd
