table inet tp7 {
  set autorizados {
    type ipv4_addr
    flags timeout
    timeout 1h
  }
  chain prerouting {
    type nat hook prerouting priority dstnat;
    iifname "brvlan30" ip saddr != @autorizados tcp dport 80 dnat ip to 192.168.30.1:8080
  }
  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    iifname "brvlan10" oifname "enp1s0" accept comment "alumnos -> Internet"
    iifname "brvlan20" oifname "enp1s0" accept comment "docentes -> Internet"
    iifname "brvlan20" oifname "brvlan10" accept comment "docentes -> alumnos"
    iifname "brvlan30" oifname "enp1s0" ip saddr @autorizados accept comment "invitados que aceptaron"
    counter log prefix "TP7-DROP "
  }
  chain postrouting {
    type nat hook postrouting priority srcnat;
    oifname "enp1s0" masquerade
  }
}
