ctrl_interface=/run/wpa_supplicant
network={
  ssid="UNCUYO-EDU"
  key_mgmt=WPA-EAP
  eap=PEAP
  identity="alumno1"
  password="alumno123"
  phase2="auth=MSCHAPV2"
  ca_cert="/etc/ssl/certs/ssl-cert-snakeoil.pem"
}
